name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04, windows-latest]
        python-version: [3.9]
    
    env:
      CONAN_HOME: ${{ github.workspace }}/.conan-home

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create virtual environment
      run: python3 -m venv .pyenv

    - name: Windows - Activate virtual environment
      if: runner.os == 'Windows'
      run: .pyenv\Scripts\activate.bat

    - name: Unix - Activate virtual environment
      if: runner.os != 'Windows'
      run: source .pyenv/bin/activate

    - name: Setup environment
      run: |
        pip3 install wheel
        pip3 install -r requirements.txt
        conan profile detect

    - name: Conan Install
      run: |
        python3 build.py conan-install --with-tests
    
    # libclang is not currently used, uncomment when needed (#17, #24)
    # - name: Cache libclang
    #   id: cache-libclang
    #   uses: actions/cache@v3
    #   env:
    #     cache-name: cache-libclang
    #   with:
    #     path: .build/_deps/libclang-subbuild/libclang-populate-prefix/src/*.7z
    #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('libclang/libclang-urls.txt') }}

    - name: Configure
      run: |
        python3 build.py configure --with-tests

    - name: Build
      run: |
        python3 build.py build

    - name: Test
      run: |
        cd .build
        ctest --verbose --output-on-failure
