name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  windows:
    name: Windows
    uses: ./.github/workflows/build-windows.yml
    with:
      python-version: '3.13'

  linux:
    name: Linux
    uses: ./.github/workflows/build-linux.yml
    with:
      python-version: '3.13'

  macos:
    name: macOS
    uses: ./.github/workflows/build-macos.yml
    with:
      python-version: '3.13'
