name: Release (Linux)

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: '3.13'

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build Release (Linux)
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04-arm]

    env:
      CONAN_HOME: ${{ github.workspace }}/.conan-home

    steps:
      - uses: actions/checkout@v5

      - name: Install prerequisites (arm64)
        if: "contains(matrix.os, 'arm')"
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt install -y gcc-11 g++-11
          ls /usr/bin/ | grep aarch64

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Create virtual environment
        run: python3 -m venv .pyenv

      - name: Activate virtual environment
        run: source .pyenv/bin/activate

      - name: Setup environment
        run: |
          pip3 install wheel
          pip3 install -r requirements.txt
          conan profile detect

      - name: Cache libclang
        uses: actions/cache@v5
        env:
          cache-name: cache-libclang
        with:
          path: .libclang-cache/download/*.7z
          key: ${{ runner.os }}-${{ runner.arch }}-build-${{ env.cache-name }}-${{ hashFiles('libclang/libclang-urls.txt') }}

      - name: Configure & Build (x86_64)
        if: "!contains(matrix.os, 'arm')"
        run: |
          ./build.py conan-install -o .conan-x86_64 -pr:h profiles/linux.release.x86_64
          ./build.py configure -t .conan-x86_64/build/Release/generators/conan_toolchain.cmake -b .build-x86_64 -bt Release
          ./build.py build -b .build-x86_64
          file .build-x86_64/opencl-language-server

      - name: Configure & Build (arm64)
        if: "contains(matrix.os, 'arm')"
        run: |
          ./build.py conan-install -o .conan-armv8 -pr:h profiles/linux.release.armv8
          ./build.py configure -t .conan-armv8/build/Release/generators/conan_toolchain.cmake -b .build-armv8 -bt Release
          ./build.py build -b .build-armv8
          file .build-armv8/opencl-language-server

      - name: Archive artifact (x86_64)
        if: "!contains(matrix.os, 'arm')"
        run: |
          cd ${{github.workspace}}/.build-x86_64/
          tar -czvf opencl-language-server-linux-x86_64.tar.gz opencl-language-server

      - name: Archive artifact (arm64)
        if: "contains(matrix.os, 'arm')"
        run: |
          cd ${{github.workspace}}/.build-armv8/
          tar -czvf opencl-language-server-linux-arm64.tar.gz opencl-language-server

      - name: Upload artifact (x86_64)
        if: "!contains(matrix.os, 'arm')"
        uses: actions/upload-artifact@v7
        with:
          name: opencl-language-server-linux-x86_64.tar.gz
          path: ${{github.workspace}}/.build-x86_64/opencl-language-server-linux-x86_64.tar.gz
          retention-days: 1
          archive: false

      - name: Upload artifact (arm64)
        if: "contains(matrix.os, 'arm')"
        uses: actions/upload-artifact@v7
        with:
          name: opencl-language-server-linux-arm64.tar.gz
          path: ${{github.workspace}}/.build-armv8/opencl-language-server-linux-arm64.tar.gz
          retention-days: 1
          archive: false

      - name: Archive licenses
        if: "!contains(matrix.os, 'arm')"
        run: |
          cd ${{github.workspace}}/.conan-x86_64
          tar -czvf licenses.tar.gz licenses

      - name: Upload licenses
        if: "!contains(matrix.os, 'arm')"
        uses: actions/upload-artifact@v7
        with:
          name: licenses.tar.gz
          path: ${{github.workspace}}/.conan-x86_64/licenses.tar.gz
          retention-days: 1
          archive: false
